name: Publish Eldora UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to hosting platform
        # Add steps to deploy to your hosting platform (e.g., Vercel, Netlify)
        # Example:
        # run: npx vercel --prod

      # Add any additional steps or integrations as needed
